<a target="_blank" href="https://colab.research.google.com/github/thinh-vu/vnstock/blob/main/docs/2_international_market.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Mục lục

1. Chứng khoán Việt Nam [tại đây](https://colab.research.google.com/github/thinh-vu/vnstock/blob/main/docs/1_vietnam_stock_vnstock3.ipynb)
2. Chứng khoán quốc tế: Forex, Crypto, Chỉ số [tại đây](https://colab.research.google.com/github/thinh-vu/vnstock/blob/main/docs/2_international_market.ipynb)
3. Dữ liệu Thị trường, hàng hoá [tại đây](https://colab.research.google.com/github/thinh-vu/vnstock/blob/main/docs/3_commodities_vnstock3.ipynb)
4. Biểu diễn dữ liệu trực quan từ Vnstock3 [tại đây](https://colab.research.google.com/github/thinh-vu/vnstock/blob/main/docs/5_visualization_data_exploration_vnstock3.ipynb)

# I. Cài đặt

## Cài đặt thư viện

In [ ]:
!pip install -U vnstock

## Nạp thư viện lần đầu

> Bạn có thể nạp toàn bộ các module của thư viện vào môi trường làm việc nếu chưa biết rõ mình cần gì hoặc chọn từng module riêng biệt để nạp vào khi đã quen thuộc.

In [1]:
## Nạp toàn bộ thư viện
# from vnstock import *

## Nạp Wrapper làm việc chính (UI chính của thư viện)
from vnstock import Vnstock

A NumPy version >=1.23.5 and <2.3.0 is required for this version of SciPy (detected version 1.23.4)

# II. Tìm kiếm mã niêm yết được hỗ trợ bởi MSN

In [2]:
from vnstock.explorer.msn.listing import Listing
Listing(api_version='20240530').search_symbol_id('USDEUR')

,symbol,symbol_id,exchange_name,exchange_code_mic,short_name,friendly_name,eng_name,description,local_name,locale
0,USDEUR,avyn9c,FOREX,FOREX,US Dollar/Euro FX Cross Rate,US Dollar/Euro FX Cross Rate,US Dollar/Euro FX Cross Rate,,US Dollar/Euro FX Cross Rate,en-us
1,,arjffr,,LU,FS - HG Bd USD (EURh) Fa,FS - HG Bd USD (EURh) Fa,Focused SICAV - High Grade Bond USD (EURh) F-a,,Focused SICAV - High Grade Bond USD (EURh) F-a,lb-lu
2,,aslrm7,,LU,UBS(L)ES-LT Thms USDEURh Pa,UBS(L)ES-LT Thms USDEURh Pa,UBS (Lux) Eq SICAV-Long Term Themes (USD)(EURh...,,UBS (Lux) Eq SICAV-Long Term Themes (USD)(EURh...,lb-lu
3,,arcg4c,,LU,FS - US CB Sus USD(EURh) Fa,FS - US CB Sus USD(EURh) Fa,Focused SICAV - US Corp Bd Sustain USD(EURh) F-a,,Focused SICAV - US Corp Bd Sustain USD(EURh) F-a,lb-lu
4,,at4aww,,LU,UBS(L)ES-LT Thms(USD)EURph Fa,UBS(L)ES-LT Thms(USD)EURph Fa,UBS (Lux) Eq SICAV-Lng Trm Thms (USD)(EURportf...,,UBS (Lux) Eq SICAV-Lng Trm Thms (USD)(EURportf...,lb-lu
5,,aswj4c,,LU,UBS L BS-GD (USD)(EURh) Pa,UBS L BS-GD (USD)(EURh) Pa,UBS (Lux) Bond S - Global Dynamic (USD)(EURh) P-a,,UBS (Lux) Bond S - Global Dynamic (USD)(EURh) P-a,lb-lu
6,,az2mzr,,LU,Focused SIC-WB Bd USD(EURh)F-a,Focused SIC-WB Bd USD(EURh)F-a,Focused SICAV-World Bank Bond USD (EUR hdg) F-acc,,Focused SICAV-World Bank Bond USD (EUR hdg) F-acc,lb-lu
7,,aslrjc,,LU,UBS(L)ES-LT Thms USDEURh Qa,UBS(L)ES-LT Thms USDEURh Qa,UBS (Lux) Eq SICAV-Long Term Themes (USD)(EURh...,,UBS (Lux) Eq SICAV-Long Term Themes (USD)(EURh...,lb-lu
8,,cen9rw,,LU,UBS L KS-Gl All USD (EURh) Pa,UBS L KS-Gl All USD (EURh) Pa,UBS (Lux) KSS-Global Allocation (USD) (EURh) Pa,,UBS (Lux) KSS-Global Allocation (USD) (EURh) Pa,lb-lu
9,,c98nxm,,LU,UBS L Eq S-USA Gr USDEURh IA1a,UBS L Eq S-USA Gr USDEURh IA1a,UBS (Lux) Eq S - USA Growth (USD) (EURh) IA1-acc,,UBS (Lux) Eq S - USA Growth (USD) (EURh) IA1-acc,lb-lu

# III. Truy xuất giá lịch sử: FX, Crypto, Index

## 3.1. Truy xuất theo mã symbol

### Forex

In [4]:
from vnstock import Vnstock
fx = Vnstock().fx(symbol='JPYVND', source='MSN')
df = fx.quote.history(start='2024-02-28', end='2025-01-14', interval='1D')
df

          time    open    high     low   close
0   2024-02-28  163.60  163.88  163.20  163.37
1   2024-02-29  163.37  165.13  163.36  164.28
2   2024-03-01  164.28  164.30  163.45  164.12
3   2024-03-04  164.15  164.43  163.76  163.92
4   2024-03-05  163.92  164.92  163.76  164.55
..         ...     ...     ...     ...     ...
224 2025-01-07  160.93  161.15  160.02  160.44
225 2025-01-08  160.44  160.66  159.97  160.20
226 2025-01-09  160.20  161.02  160.14  160.45
227 2025-01-10  160.48  161.29  159.60  160.79
228 2025-01-13  160.71  161.80  160.52  161.22

[229 rows x 5 columns]

### Crypto

In [5]:
crypto = Vnstock().crypto(symbol='BTC', source='MSN')
df = crypto.quote.history(start='2023-01-01', end='2024-12-31', interval='1D')
df

,time,open,high,low,close,volume
151,2023-01-07,4.272255e+08,4.311719e+08,4.241792e+08,4.301562e+08,365746696410270
152,2023-02-06,5.920558e+08,5.943697e+08,5.796097e+08,5.825000e+08,496443163607203
153,2023-03-08,5.691187e+08,5.716332e+08,5.585358e+08,5.638266e+08,577673349675738
154,2023-04-07,7.149464e+08,7.150265e+08,7.038710e+08,7.116200e+08,351134413024605
155,2023-05-07,7.495485e+08,7.566857e+08,7.224000e+08,7.334548e+08,403814367879676
156,2023-06-06,6.882489e+08,6.884233e+08,6.456711e+08,6.536625e+08,545899800904430
157,2023-07-06,7.810102e+08,7.835122e+08,7.669749e+08,7.742970e+08,316721165343581
158,2023-08-05,7.402999e+08,7.435402e+08,7.329654e+08,7.377551e+08,305429739685857
159,2023-09-04,6.564379e+08,6.619614e+08,6.551072e+08,6.589778e+08,227424059770871
160,2023-10-04,6.980219e+08,7.020550e+08,6.906060e+08,6.960357e+08,289473284984721
161,2023-11-03,8.993300e+08,9.114660e+08,8.729400e+08,8.865579e+08,532828273059836
162,2023-12-03,9.817404e+08,1.006853e+09,9.808096e+08,1.001712e+09,394176153652977
163,2024-01-02,1.072861e+09,1.120952e+09,1.071205e+09,1.120746e+09,467584577997468
164,2024-02-01,1.089761e+09,1.109329e+09,1.073336e+09,1.080534e+09,626093330626435
165,2024-03-02,1.552140e+09,1.602561e+09,1.542864e+09,1.584431e+09,1019729098732356
166,2024-04-01,1.767312e+09,1.811211e+09,1.766731e+09,1.810091e+09,508792637335561
167,2024-05-01,1.619925e+09,1.641847e+09,1.500172e+09,1.538660e+09,960211316451703
168,2024-05-31,1.714743e+09,1.763576e+09,1.703121e+09,1.734762e+09,748808955544921
169,2024-06-30,1.530617e+09,1.550352e+09,1.530137e+09,1.545017e+09,321067423670201
170,2024-07-30,1.732074e+09,1.775934e+09,1.688265e+09,1.695555e+09,1034809821686515
171,2024-08-29,1.510014e+09,1.528500e+09,1.468976e+09,1.497826e+09,1022347704218093
172,2024-09-28,1.653959e+09,1.686948e+09,1.645645e+09,1.669438e+09,813492391278525
173,2024-10-28,1.700721e+09,1.731116e+09,1.696248e+09,1.723706e+09,424303187406787
174,2024-11-27,2.362090e+09,2.410416e+09,2.303309e+09,2.334127e+09,2325784191331282
175,2024-12-27,2.519679e+09,2.534571e+09,2.414124e+09,2.430811e+09,1194020139658972

### Index

In [6]:
index = Vnstock().world_index(symbol='DJI', source='MSN')
df = index.quote.history(start='2023-01-01', end='2024-12-31', interval='1D')
df

          time      open      high       low     close     volume
138 2023-07-24  35230.79  35463.97  35230.79  35411.24  286173242
139 2023-07-25  35421.49  35527.57  35365.26  35438.07  309326664
140 2023-07-26  35345.99  35633.61  35306.27  35520.12  347334097
141 2023-07-27  35558.79  35645.35  35216.58  35282.72  352233629
142 2023-07-28  35443.49  35565.51  35355.15  35459.29  369000609
..         ...       ...       ...       ...       ...        ...
498 2024-12-25  42916.48  43297.65  42871.76  43297.03  -99999902
499 2024-12-26  43201.85  43373.98  43115.09  43325.80  270359363
500 2024-12-27  43142.37  43238.85  42761.56  42992.21  376962934
501 2024-12-30  42863.86  42863.86  42263.51  42573.73  383300069
502 2024-12-31  42636.70  42779.69  42421.29  42544.22  359219218

[365 rows x 6 columns]

## 3.2. Truy xuất theo id tương ứng symbol

Trong trường hợp mã symbol bạn cần không có sẵn trong danh sách được hỗ trợ, bạn có thể truy xuất dữ liệu theo id của mã đó được tìm kiếm ở mục `II. Tìm kiếm mã niêm yết được hỗ trợ bởi MSN`

In [7]:
# avyufr là symbol_id của USDEUR
from vnstock.explorer.msn.quote import *

fx = Quote(symbol_id='avyn9c')
fx.history(start='2020-01-01', end='2024-12-31')

           time  open  high   low  close
940  2023-08-09  0.91  0.91  0.91   0.91
941  2023-08-10  0.91  0.91   0.9   0.91
942  2023-08-11  0.91  0.91  0.91   0.91
943  2023-08-14  0.91  0.92  0.91   0.92
944  2023-08-15  0.92  0.92  0.91   0.92
...         ...   ...   ...   ...    ...
1300 2024-12-25  0.96  0.96  0.96   0.96
1301 2024-12-26  0.96  0.96  0.96   0.96
1302 2024-12-27  0.96  0.96  0.96   0.96
1303 2024-12-30  0.96  0.96  0.96   0.96
1304 2024-12-31  0.96  0.97  0.96   0.97

[365 rows x 5 columns]

In [8]:
# c2111 là symbol_id của BTC
crypto = Quote(symbol_id='c2111')
crypto.history(start='2023-01-01', end='2024-12-31', interval='1D')

,time,open,high,low,close,volume
151,2023-01-07,4.272255e+08,4.311719e+08,4.241792e+08,4.301562e+08,365746696410270
152,2023-02-06,5.920558e+08,5.943697e+08,5.796097e+08,5.825000e+08,496443163607203
153,2023-03-08,5.691187e+08,5.716332e+08,5.585358e+08,5.638266e+08,577673349675738
154,2023-04-07,7.149464e+08,7.150265e+08,7.038710e+08,7.116200e+08,351134413024605
155,2023-05-07,7.495485e+08,7.566857e+08,7.224000e+08,7.334548e+08,403814367879676
156,2023-06-06,6.882489e+08,6.884233e+08,6.456711e+08,6.536625e+08,545899800904430
157,2023-07-06,7.810102e+08,7.835122e+08,7.669749e+08,7.742970e+08,316721165343581
158,2023-08-05,7.402999e+08,7.435402e+08,7.329654e+08,7.377551e+08,305429739685857
159,2023-09-04,6.564379e+08,6.619614e+08,6.551072e+08,6.589778e+08,227424059770871
160,2023-10-04,6.980219e+08,7.020550e+08,6.906060e+08,6.960357e+08,289473284984721
161,2023-11-03,8.993300e+08,9.114660e+08,8.729400e+08,8.865579e+08,532828273059836
162,2023-12-03,9.817404e+08,1.006853e+09,9.808096e+08,1.001712e+09,394176153652977
163,2024-01-02,1.072861e+09,1.120952e+09,1.071205e+09,1.120746e+09,467584577997468
164,2024-02-01,1.089761e+09,1.109329e+09,1.073336e+09,1.080534e+09,626093330626435
165,2024-03-02,1.552140e+09,1.602561e+09,1.542864e+09,1.584431e+09,1019729098732356
166,2024-04-01,1.767312e+09,1.811211e+09,1.766731e+09,1.810091e+09,508792637335561
167,2024-05-01,1.619925e+09,1.641847e+09,1.500172e+09,1.538660e+09,960211316451703
168,2024-05-31,1.714743e+09,1.763576e+09,1.703121e+09,1.734762e+09,748808955544921
169,2024-06-30,1.530617e+09,1.550352e+09,1.530137e+09,1.545017e+09,321067423670201
170,2024-07-30,1.732074e+09,1.775934e+09,1.688265e+09,1.695555e+09,1034809821686515
171,2024-08-29,1.510014e+09,1.528500e+09,1.468976e+09,1.497826e+09,1022347704218093
172,2024-09-28,1.653959e+09,1.686948e+09,1.645645e+09,1.669438e+09,813492391278525
173,2024-10-28,1.700721e+09,1.731116e+09,1.696248e+09,1.723706e+09,424303187406787
174,2024-11-27,2.362090e+09,2.410416e+09,2.303309e+09,2.334127e+09,2325784191331282
175,2024-12-27,2.519679e+09,2.534571e+09,2.414124e+09,2.430811e+09,1194020139658972